// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXX-lYRXG21MLlA35tiz67pOWgfMys6OY',
    appId: '1:1010978308032:web:56b55eaf711e82fbcdd225',
    messagingSenderId: '1010978308032',
    projectId: 'gitroops-84d8e',
    authDomain: 'gitroops-84d8e.firebaseapp.com',
    storageBucket: 'gitroops-84d8e.appspot.com',
    measurementId: 'G-830673BC51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxi04opCXDryNPAVBp2IFfuRCHqa1h9w',
    appId: '1:1010978308032:android:12dcd6dcd0c7d4a5cdd225',
    messagingSenderId: '1010978308032',
    projectId: 'gitroops-84d8e',
    storageBucket: 'gitroops-84d8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4dFeS6BZpSRJLHrNOOQmeN06lRBkIIag',
    appId: '1:1010978308032:ios:ba6a9058e8fb60f3cdd225',
    messagingSenderId: '1010978308032',
    projectId: 'gitroops-84d8e',
    storageBucket: 'gitroops-84d8e.appspot.com',
    iosClientId: '1010978308032-ahm0vts0h8sct2fckadhquqgmjdcipqo.apps.googleusercontent.com',
    iosBundleId: 'dev.widdyjp.gitaGitroops',
  );
}
